name: Heroku - BPR

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 #This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME_1}} #Heroku App Name that will be pushed out
          heroku_email: ${{secrets.HEROKU_EMAIL}} #Your Heroku Login Email
          remote_branch: master # <- Include this:
          stack: "heroku-20"
          buildpack: ${{secrets.HEROKU_BUILDPACK_1}}
          appdir: /server
      - uses: akhileshns/heroku-deploy@v3.12.12 #This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME_2}} #Heroku App Name that will be pushed out
          heroku_email: ${{secrets.HEROKU_EMAIL}} #Your Heroku Login Email
          remote_branch: master # <- Include this:
          stack: "heroku-20"
          buildpack: ${{secrets.HEROKU_BUILDPACK_2}}
          appdir: /server
      - name: Ping Site
        run: |
          sudo apt-get install -y curl && \
          curl ${{secrets.HEROKU_APP_NAME_1}}.herokuapp.com && \
          curl ${{secrets.HEROKU_APP_NAME_2}}.herokuapp.com

